### PR TITLE
Issue #9

### PR DESCRIPTION
**Pull request by rredpoppy**
Charset from string as per issue #9

### CODE REVIEW

**Comment by yogthos** [comment]
thanks

**Comment by yogthos** [comment]
It does look like a string is supposed to be passed here though:

```
testing Js minifcation
expected: (clojure.core/= (asset-minifier.core-test/massage-data {:warnings ["JSC_UNDEFINED_EXTERN_VAR_ERROR. name hljs is not undefined in the externs. at test/resources/js/externs.js line 1 : 0"], :errors (), :sources ["input2.js"], :target "output.min.js", :original-size 2409, :compressed-size 1254, :gzipped-size 621}) (asset-minifier.core-test/massage-data (minify-js (str input-path "/js/input2.js") (str output-path "output.min.js") {:optimization :advanced, :externs [(str input-path "/js/externs.js")]})))
  actual: java.lang.ClassCastException: sun.nio.cs.UTF_8 cannot be cast to java.lang.String
```

**Comment by rredpoppy** [comment]
saw that, sorry I didn't have time to look at tests too. probably a version increase should have been in order too

**Comment by yogthos** [comment]
No worries, I just updated the dependencies and got the tests passing. I pushed out a new version to Clojars with the fixes.

**Pull request merged**
