### PR TITLE
Language option

### PR DESCRIPTION
**Pull request by SerCeMan**
Ability to set language option for avoiding the "trailing comma" problem

### CODE REVIEW

**Comment by yogthos** [comment]
looks good, should there be a default for the language maybe?

**Comment by SerCeMan** [comment]
> should there be a default for the language maybe?
I think it does not matter, ecmasript3 is default for closure compiler

**Comment by yogthos** [comment]
ah my bad missed that

**Comment by yogthos** [comment]
ok it's up on clojars :)

**Comment by SerCeMan** [comment]
Thank you very much

**Pull request merged**
